//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from t2l.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace T2L.Antlr {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="t2lParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface It2lListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] t2lParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] t2lParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] t2lParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] t2lParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] t2lParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] t2lParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.class_stat_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_stat_block([NotNull] t2lParser.Class_stat_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.class_stat_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_stat_block([NotNull] t2lParser.Class_stat_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.call_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_stat([NotNull] t2lParser.Call_statContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.call_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_stat([NotNull] t2lParser.Call_statContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.func_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_stat([NotNull] t2lParser.Func_statContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.func_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_stat([NotNull] t2lParser.Func_statContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.t2l_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterT2l_return([NotNull] t2lParser.T2l_returnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.t2l_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitT2l_return([NotNull] t2lParser.T2l_returnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.class_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_stat([NotNull] t2lParser.Class_statContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.class_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_stat([NotNull] t2lParser.Class_statContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParams([NotNull] t2lParser.ParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParams([NotNull] t2lParser.ParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.def_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDef_params([NotNull] t2lParser.Def_paramsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.def_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDef_params([NotNull] t2lParser.Def_paramsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] t2lParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] t2lParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex([NotNull] t2lParser.IndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex([NotNull] t2lParser.IndexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.import_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_stat([NotNull] t2lParser.Import_statContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.import_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_stat([NotNull] t2lParser.Import_statContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.jimport_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJimport_stat([NotNull] t2lParser.Jimport_statContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.jimport_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJimport_stat([NotNull] t2lParser.Jimport_statContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.if_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_stat([NotNull] t2lParser.If_statContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.if_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_stat([NotNull] t2lParser.If_statContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.elseIfStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfStat([NotNull] t2lParser.ElseIfStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.elseIfStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfStat([NotNull] t2lParser.ElseIfStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.elseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStat([NotNull] t2lParser.ElseStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.elseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStat([NotNull] t2lParser.ElseStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCond([NotNull] t2lParser.CondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCond([NotNull] t2lParser.CondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.stat_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat_block([NotNull] t2lParser.Stat_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.stat_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat_block([NotNull] t2lParser.Stat_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.while_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_stat([NotNull] t2lParser.While_statContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.while_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_stat([NotNull] t2lParser.While_statContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.for_loop_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_loop_stat([NotNull] t2lParser.For_loop_statContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.for_loop_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_loop_stat([NotNull] t2lParser.For_loop_statContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DictionaryOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictionaryOp([NotNull] t2lParser.DictionaryOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DictionaryOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictionaryOp([NotNull] t2lParser.DictionaryOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ClassOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOp([NotNull] t2lParser.ClassOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ClassOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOp([NotNull] t2lParser.ClassOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ListOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListOp([NotNull] t2lParser.ListOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ListOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListOp([NotNull] t2lParser.ListOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FuncOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncOp([NotNull] t2lParser.FuncOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FuncOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncOp([NotNull] t2lParser.FuncOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AtomOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomOp([NotNull] t2lParser.AtomOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AtomOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomOp([NotNull] t2lParser.AtomOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiOp([NotNull] t2lParser.MultiOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiOp([NotNull] t2lParser.MultiOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprOp([NotNull] t2lParser.ExprOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprOp([NotNull] t2lParser.ExprOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleOp([NotNull] t2lParser.SingleOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleOp([NotNull] t2lParser.SingleOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IndexOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexOp([NotNull] t2lParser.IndexOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IndexOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexOp([NotNull] t2lParser.IndexOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="t2lParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] t2lParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="t2lParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] t2lParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenAtom([NotNull] t2lParser.ParenAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenAtom([NotNull] t2lParser.ParenAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IntAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntAtom([NotNull] t2lParser.IntAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IntAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntAtom([NotNull] t2lParser.IntAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IDAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIDAtom([NotNull] t2lParser.IDAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IDAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIDAtom([NotNull] t2lParser.IDAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StringAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringAtom([NotNull] t2lParser.StringAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StringAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringAtom([NotNull] t2lParser.StringAtomContext context);
}
} // namespace T2L.Antlr
