//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from t2l.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace T2L.Antlr {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public partial class t2lParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, OR=2, AND=3, EQ=4, NEQ=5, GT=6, LT=7, GTEQ=8, LTEQ=9, PLUS=10, 
		MINUS=11, MULT=12, DIV=13, MOD=14, POW=15, NOT=16, SCOL=17, COL=18, ASSIGN=19, 
		COMMA=20, OPAR=21, CPAR=22, OBRACE=23, CBRACE=24, OSQUARE=25, CSQUARE=26, 
		IF=27, ELSE=28, WHILE=29, FOR=30, IN=31, FUNC=32, T2L_RETURN=33, CLASS=34, 
		NEW=35, IMPORT=36, JIMPORT=37, ID=38, INT=39, DOC=40, STRING=41, COMMENT=42, 
		SPACE=43;
	public const int
		RULE_start = 0, RULE_block = 1, RULE_stat = 2, RULE_class_stat_block = 3, 
		RULE_call_stat = 4, RULE_func_stat = 5, RULE_t2l_return = 6, RULE_class_stat = 7, 
		RULE_params = 8, RULE_def_params = 9, RULE_var = 10, RULE_index = 11, 
		RULE_import_stat = 12, RULE_jimport_stat = 13, RULE_if_stat = 14, RULE_elseIfStat = 15, 
		RULE_elseStat = 16, RULE_cond = 17, RULE_stat_block = 18, RULE_while_stat = 19, 
		RULE_for_loop_stat = 20, RULE_expr = 21, RULE_pair = 22, RULE_atom = 23;
	public static readonly string[] ruleNames = {
		"start", "block", "stat", "class_stat_block", "call_stat", "func_stat", 
		"t2l_return", "class_stat", "params", "def_params", "var", "index", "import_stat", 
		"jimport_stat", "if_stat", "elseIfStat", "elseStat", "cond", "stat_block", 
		"while_stat", "for_loop_stat", "expr", "pair", "atom"
	};

	private static readonly string[] _LiteralNames = {
		null, "'.'", "'||'", "'&&'", "'=='", "'!='", "'>'", "'<'", "'>='", "'<='", 
		"'+'", "'-'", "'*'", "'/'", "'%'", "'^'", "'!'", "';'", "':'", "'='", 
		"','", "'('", "')'", "'{'", "'}'", "'['", "']'", "'if'", "'else'", "'while'", 
		"'for'", "'in'", "'func'", "'return'", "'class'", "'new'", "'import'", 
		"'jimport'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "OR", "AND", "EQ", "NEQ", "GT", "LT", "GTEQ", "LTEQ", "PLUS", 
		"MINUS", "MULT", "DIV", "MOD", "POW", "NOT", "SCOL", "COL", "ASSIGN", 
		"COMMA", "OPAR", "CPAR", "OBRACE", "CBRACE", "OSQUARE", "CSQUARE", "IF", 
		"ELSE", "WHILE", "FOR", "IN", "FUNC", "T2L_RETURN", "CLASS", "NEW", "IMPORT", 
		"JIMPORT", "ID", "INT", "DOC", "STRING", "COMMENT", "SPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "t2l.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static t2lParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public t2lParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public t2lParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StartContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public StartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_start; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterStart(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitStart(this);
		}
	}

	[RuleVersion(0)]
	public StartContext start() {
		StartContext _localctx = new StartContext(Context, State);
		EnterRule(_localctx, 0, RULE_start);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48;
			block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatContext[] stat() {
			return GetRuleContexts<StatContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatContext stat(int i) {
			return GetRuleContext<StatContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF) | (1L << WHILE) | (1L << FOR) | (1L << FUNC) | (1L << T2L_RETURN) | (1L << CLASS) | (1L << IMPORT) | (1L << JIMPORT) | (1L << ID) | (1L << DOC))) != 0)) {
				{
				{
				State = 50;
				stat();
				}
				}
				State = 55;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VarContext var() {
			return GetRuleContext<VarContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public If_statContext if_stat() {
			return GetRuleContext<If_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public While_statContext while_stat() {
			return GetRuleContext<While_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Call_statContext call_stat() {
			return GetRuleContext<Call_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_statContext func_stat() {
			return GetRuleContext<Func_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_statContext class_stat() {
			return GetRuleContext<Class_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public T2l_returnContext t2l_return() {
			return GetRuleContext<T2l_returnContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IndexContext index() {
			return GetRuleContext<IndexContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public For_loop_statContext for_loop_stat() {
			return GetRuleContext<For_loop_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Import_statContext import_stat() {
			return GetRuleContext<Import_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Jimport_statContext jimport_stat() {
			return GetRuleContext<Jimport_statContext>(0);
		}
		public StatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterStat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitStat(this);
		}
	}

	[RuleVersion(0)]
	public StatContext stat() {
		StatContext _localctx = new StatContext(Context, State);
		EnterRule(_localctx, 4, RULE_stat);
		try {
			State = 67;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 56;
				var();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 57;
				if_stat();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 58;
				while_stat();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 59;
				call_stat();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 60;
				func_stat();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 61;
				class_stat();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 62;
				t2l_return();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 63;
				index();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 64;
				for_loop_stat();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 65;
				import_stat();
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 66;
				jimport_stat();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Class_stat_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VarContext var() {
			return GetRuleContext<VarContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_statContext class_stat() {
			return GetRuleContext<Class_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_statContext func_stat() {
			return GetRuleContext<Func_statContext>(0);
		}
		public Class_stat_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_class_stat_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterClass_stat_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitClass_stat_block(this);
		}
	}

	[RuleVersion(0)]
	public Class_stat_blockContext class_stat_block() {
		Class_stat_blockContext _localctx = new Class_stat_blockContext(Context, State);
		EnterRule(_localctx, 6, RULE_class_stat_block);
		try {
			State = 72;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 69;
				var();
				}
				break;
			case CLASS:
				EnterOuterAlt(_localctx, 2);
				{
				State = 70;
				class_stat();
				}
				break;
			case FUNC:
			case DOC:
				EnterOuterAlt(_localctx, 3);
				{
				State = 71;
				func_stat();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Call_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParamsContext @params() {
			return GetRuleContext<ParamsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public Call_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterCall_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitCall_stat(this);
		}
	}

	[RuleVersion(0)]
	public Call_statContext call_stat() {
		Call_statContext _localctx = new Call_statContext(Context, State);
		EnterRule(_localctx, 8, RULE_call_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			Match(ID);
			State = 75;
			Match(OPAR);
			State = 76;
			@params();
			State = 77;
			Match(CPAR);
			State = 78;
			Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FUNC() { return GetToken(t2lParser.FUNC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Def_paramsContext def_params() {
			return GetRuleContext<Def_paramsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOC() { return GetToken(t2lParser.DOC, 0); }
		public Func_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterFunc_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitFunc_stat(this);
		}
	}

	[RuleVersion(0)]
	public Func_statContext func_stat() {
		Func_statContext _localctx = new Func_statContext(Context, State);
		EnterRule(_localctx, 10, RULE_func_stat);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DOC) {
				{
				State = 80;
				Match(DOC);
				}
			}

			State = 83;
			Match(FUNC);
			State = 84;
			Match(ID);
			State = 85;
			def_params();
			State = 86;
			stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class T2l_returnContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T2L_RETURN() { return GetToken(t2lParser.T2L_RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public T2l_returnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_t2l_return; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterT2l_return(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitT2l_return(this);
		}
	}

	[RuleVersion(0)]
	public T2l_returnContext t2l_return() {
		T2l_returnContext _localctx = new T2l_returnContext(Context, State);
		EnterRule(_localctx, 12, RULE_t2l_return);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			Match(T2L_RETURN);
			State = 89;
			expr(0);
			State = 90;
			Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Class_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(t2lParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(t2lParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(t2lParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBRACE() { return GetToken(t2lParser.OBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CBRACE() { return GetToken(t2lParser.CBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Class_stat_blockContext[] class_stat_block() {
			return GetRuleContexts<Class_stat_blockContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_stat_blockContext class_stat_block(int i) {
			return GetRuleContext<Class_stat_blockContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(t2lParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(t2lParser.COMMA, i);
		}
		public Class_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_class_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterClass_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitClass_stat(this);
		}
	}

	[RuleVersion(0)]
	public Class_statContext class_stat() {
		Class_statContext _localctx = new Class_statContext(Context, State);
		EnterRule(_localctx, 14, RULE_class_stat);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			Match(CLASS);
			State = 93;
			Match(ID);
			State = 104;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==OPAR) {
				{
				State = 94;
				Match(OPAR);
				State = 99;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 95;
						Match(ID);
						State = 96;
						Match(COMMA);
						}
						} 
					}
					State = 101;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				}
				State = 102;
				Match(ID);
				State = 103;
				Match(CPAR);
				}
			}

			State = 106;
			Match(OBRACE);
			State = 110;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << FUNC) | (1L << CLASS) | (1L << ID) | (1L << DOC))) != 0)) {
				{
				{
				State = 107;
				class_stat_block();
				}
				}
				State = 112;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 113;
			Match(CBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParamsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(t2lParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(t2lParser.COMMA, i);
		}
		public ParamsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_params; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterParams(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitParams(this);
		}
	}

	[RuleVersion(0)]
	public ParamsContext @params() {
		ParamsContext _localctx = new ParamsContext(Context, State);
		EnterRule(_localctx, 16, RULE_params);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MINUS) | (1L << NOT) | (1L << OPAR) | (1L << OBRACE) | (1L << OSQUARE) | (1L << NEW) | (1L << ID) | (1L << INT) | (1L << STRING))) != 0)) {
				{
				State = 120;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 115;
						expr(0);
						State = 116;
						Match(COMMA);
						}
						} 
					}
					State = 122;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
				}
				State = 123;
				expr(0);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Def_paramsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(t2lParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(t2lParser.STRING, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(t2lParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(t2lParser.COMMA, i);
		}
		public Def_paramsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_def_params; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterDef_params(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitDef_params(this);
		}
	}

	[RuleVersion(0)]
	public Def_paramsContext def_params() {
		Def_paramsContext _localctx = new Def_paramsContext(Context, State);
		EnterRule(_localctx, 18, RULE_def_params);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 134;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==STRING) {
				{
				State = 130;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 126;
						Match(STRING);
						State = 127;
						Match(COMMA);
						}
						} 
					}
					State = 132;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
				}
				State = 133;
				Match(STRING);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(t2lParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public VarContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterVar(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitVar(this);
		}
	}

	[RuleVersion(0)]
	public VarContext var() {
		VarContext _localctx = new VarContext(Context, State);
		EnterRule(_localctx, 20, RULE_var);
		try {
			State = 143;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 136;
				Match(ID);
				State = 137;
				Match(ASSIGN);
				State = 138;
				expr(0);
				State = 139;
				Match(SCOL);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 141;
				Match(ID);
				State = 142;
				Match(SCOL);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IndexContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OSQUARE() { return GetToken(t2lParser.OSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CSQUARE() { return GetToken(t2lParser.CSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(t2lParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public IndexContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_index; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterIndex(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitIndex(this);
		}
	}

	[RuleVersion(0)]
	public IndexContext index() {
		IndexContext _localctx = new IndexContext(Context, State);
		EnterRule(_localctx, 22, RULE_index);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 145;
			Match(ID);
			State = 146;
			Match(OSQUARE);
			State = 147;
			expr(0);
			State = 148;
			Match(CSQUARE);
			State = 149;
			Match(ASSIGN);
			State = 150;
			expr(0);
			State = 151;
			Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Import_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IMPORT() { return GetToken(t2lParser.IMPORT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public Import_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_import_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterImport_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitImport_stat(this);
		}
	}

	[RuleVersion(0)]
	public Import_statContext import_stat() {
		Import_statContext _localctx = new Import_statContext(Context, State);
		EnterRule(_localctx, 24, RULE_import_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153;
			Match(IMPORT);
			State = 154;
			Match(ID);
			State = 155;
			Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Jimport_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode JIMPORT() { return GetToken(t2lParser.JIMPORT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public Jimport_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jimport_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterJimport_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitJimport_stat(this);
		}
	}

	[RuleVersion(0)]
	public Jimport_statContext jimport_stat() {
		Jimport_statContext _localctx = new Jimport_statContext(Context, State);
		EnterRule(_localctx, 26, RULE_jimport_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 157;
			Match(JIMPORT);
			State = 158;
			Match(ID);
			State = 159;
			Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class If_statContext : ParserRuleContext {
		public ElseIfStatContext ElseIf;
		public ElseStatContext Else;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(t2lParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CondContext cond() {
			return GetRuleContext<CondContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElseIfStatContext[] elseIfStat() {
			return GetRuleContexts<ElseIfStatContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElseIfStatContext elseIfStat(int i) {
			return GetRuleContext<ElseIfStatContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElseStatContext elseStat() {
			return GetRuleContext<ElseStatContext>(0);
		}
		public If_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterIf_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitIf_stat(this);
		}
	}

	[RuleVersion(0)]
	public If_statContext if_stat() {
		If_statContext _localctx = new If_statContext(Context, State);
		EnterRule(_localctx, 28, RULE_if_stat);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 161;
			Match(IF);
			State = 162;
			cond();
			State = 166;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 163;
					_localctx.ElseIf = elseIfStat();
					}
					} 
				}
				State = 168;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			}
			State = 170;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 169;
				_localctx.Else = elseStat();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElseIfStatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(t2lParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(t2lParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CondContext cond() {
			return GetRuleContext<CondContext>(0);
		}
		public ElseIfStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elseIfStat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterElseIfStat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitElseIfStat(this);
		}
	}

	[RuleVersion(0)]
	public ElseIfStatContext elseIfStat() {
		ElseIfStatContext _localctx = new ElseIfStatContext(Context, State);
		EnterRule(_localctx, 30, RULE_elseIfStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 172;
			Match(ELSE);
			State = 173;
			Match(IF);
			State = 174;
			cond();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElseStatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(t2lParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public ElseStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elseStat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterElseStat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitElseStat(this);
		}
	}

	[RuleVersion(0)]
	public ElseStatContext elseStat() {
		ElseStatContext _localctx = new ElseStatContext(Context, State);
		EnterRule(_localctx, 32, RULE_elseStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			Match(ELSE);
			State = 177;
			stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CondContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public CondContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cond; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterCond(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitCond(this);
		}
	}

	[RuleVersion(0)]
	public CondContext cond() {
		CondContext _localctx = new CondContext(Context, State);
		EnterRule(_localctx, 34, RULE_cond);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 179;
			expr(0);
			State = 180;
			stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Stat_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBRACE() { return GetToken(t2lParser.OBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CBRACE() { return GetToken(t2lParser.CBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatContext stat() {
			return GetRuleContext<StatContext>(0);
		}
		public Stat_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stat_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterStat_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitStat_block(this);
		}
	}

	[RuleVersion(0)]
	public Stat_blockContext stat_block() {
		Stat_blockContext _localctx = new Stat_blockContext(Context, State);
		EnterRule(_localctx, 36, RULE_stat_block);
		try {
			State = 187;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OBRACE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 182;
				Match(OBRACE);
				State = 183;
				block();
				State = 184;
				Match(CBRACE);
				}
				break;
			case IF:
			case WHILE:
			case FOR:
			case FUNC:
			case T2L_RETURN:
			case CLASS:
			case IMPORT:
			case JIMPORT:
			case ID:
			case DOC:
				EnterOuterAlt(_localctx, 2);
				{
				State = 186;
				stat();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class While_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(t2lParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public While_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterWhile_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitWhile_stat(this);
		}
	}

	[RuleVersion(0)]
	public While_statContext while_stat() {
		While_statContext _localctx = new While_statContext(Context, State);
		EnterRule(_localctx, 38, RULE_while_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 189;
			Match(WHILE);
			State = 190;
			expr(0);
			State = 191;
			stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_loop_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR() { return GetToken(t2lParser.FOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IN() { return GetToken(t2lParser.IN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public For_loop_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_loop_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterFor_loop_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitFor_loop_stat(this);
		}
	}

	[RuleVersion(0)]
	public For_loop_statContext for_loop_stat() {
		For_loop_statContext _localctx = new For_loop_statContext(Context, State);
		EnterRule(_localctx, 40, RULE_for_loop_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 193;
			Match(FOR);
			State = 194;
			Match(ID);
			State = 195;
			Match(IN);
			State = 196;
			expr(0);
			State = 197;
			stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DictionaryOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBRACE() { return GetToken(t2lParser.OBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CBRACE() { return GetToken(t2lParser.CBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(t2lParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(t2lParser.COMMA, i);
		}
		public DictionaryOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterDictionaryOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitDictionaryOp(this);
		}
	}
	public partial class ClassOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW() { return GetToken(t2lParser.NEW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParamsContext @params() {
			return GetRuleContext<ParamsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		public ClassOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterClassOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitClassOp(this);
		}
	}
	public partial class ListOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OSQUARE() { return GetToken(t2lParser.OSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CSQUARE() { return GetToken(t2lParser.CSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(t2lParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(t2lParser.COMMA, i);
		}
		public ListOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterListOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitListOp(this);
		}
	}
	public partial class FuncOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParamsContext @params() {
			return GetRuleContext<ParamsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		public FuncOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterFuncOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitFuncOp(this);
		}
	}
	public partial class AtomOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public AtomOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterAtomOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitAtomOp(this);
		}
	}
	public partial class MultiOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public MultiOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterMultiOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitMultiOp(this);
		}
	}
	public partial class ExprOpContext : ExprContext {
		public ExprContext left;
		public IToken op;
		public ExprContext right;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode POW() { return GetToken(t2lParser.POW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT() { return GetToken(t2lParser.MULT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(t2lParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD() { return GetToken(t2lParser.MOD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(t2lParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(t2lParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LTEQ() { return GetToken(t2lParser.LTEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GTEQ() { return GetToken(t2lParser.GTEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(t2lParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(t2lParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(t2lParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEQ() { return GetToken(t2lParser.NEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(t2lParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(t2lParser.OR, 0); }
		public ExprOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitExprOp(this);
		}
	}
	public partial class SingleOpContext : ExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(t2lParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(t2lParser.NOT, 0); }
		public SingleOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterSingleOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitSingleOp(this);
		}
	}
	public partial class IndexOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OSQUARE() { return GetToken(t2lParser.OSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CSQUARE() { return GetToken(t2lParser.CSQUARE, 0); }
		public IndexOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterIndexOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitIndexOp(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 42;
		EnterRecursionRule(_localctx, 42, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 247;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				{
				_localctx = new SingleOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 200;
				((SingleOpContext)_localctx).op = Match(MINUS);
				State = 201;
				expr(15);
				}
				break;
			case 2:
				{
				_localctx = new SingleOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 202;
				((SingleOpContext)_localctx).op = Match(NOT);
				State = 203;
				expr(14);
				}
				break;
			case 3:
				{
				_localctx = new AtomOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 204;
				atom();
				}
				break;
			case 4:
				{
				_localctx = new ListOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 205;
				Match(OSQUARE);
				State = 215;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MINUS) | (1L << NOT) | (1L << OPAR) | (1L << OBRACE) | (1L << OSQUARE) | (1L << NEW) | (1L << ID) | (1L << INT) | (1L << STRING))) != 0)) {
					{
					State = 211;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
					while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
						if ( _alt==1 ) {
							{
							{
							State = 206;
							expr(0);
							State = 207;
							Match(COMMA);
							}
							} 
						}
						State = 213;
						ErrorHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
					}
					State = 214;
					expr(0);
					}
				}

				State = 217;
				Match(CSQUARE);
				}
				break;
			case 5:
				{
				_localctx = new DictionaryOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 218;
				Match(OBRACE);
				State = 228;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MINUS) | (1L << NOT) | (1L << OPAR) | (1L << OBRACE) | (1L << OSQUARE) | (1L << NEW) | (1L << ID) | (1L << INT) | (1L << STRING))) != 0)) {
					{
					State = 224;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
					while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
						if ( _alt==1 ) {
							{
							{
							State = 219;
							pair();
							State = 220;
							Match(COMMA);
							}
							} 
						}
						State = 226;
						ErrorHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
					}
					State = 227;
					pair();
					}
				}

				State = 230;
				Match(CBRACE);
				}
				break;
			case 6:
				{
				_localctx = new IndexOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 231;
				Match(ID);
				State = 232;
				Match(OSQUARE);
				State = 233;
				expr(0);
				State = 234;
				Match(CSQUARE);
				}
				break;
			case 7:
				{
				_localctx = new FuncOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 236;
				Match(ID);
				State = 237;
				Match(OPAR);
				State = 238;
				@params();
				State = 239;
				Match(CPAR);
				}
				break;
			case 8:
				{
				_localctx = new ClassOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 241;
				Match(NEW);
				State = 242;
				Match(ID);
				State = 243;
				Match(OPAR);
				State = 244;
				@params();
				State = 245;
				Match(CPAR);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 275;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 273;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
					case 1:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 249;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 250;
						((ExprOpContext)_localctx).op = Match(POW);
						State = 251;
						((ExprOpContext)_localctx).right = expr(16);
						}
						break;
					case 2:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 252;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 253;
						((ExprOpContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MULT) | (1L << DIV) | (1L << MOD))) != 0)) ) {
							((ExprOpContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 254;
						((ExprOpContext)_localctx).right = expr(14);
						}
						break;
					case 3:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 255;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 256;
						((ExprOpContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((ExprOpContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 257;
						((ExprOpContext)_localctx).right = expr(13);
						}
						break;
					case 4:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 258;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 259;
						((ExprOpContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << GT) | (1L << LT) | (1L << GTEQ) | (1L << LTEQ))) != 0)) ) {
							((ExprOpContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 260;
						((ExprOpContext)_localctx).right = expr(12);
						}
						break;
					case 5:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 261;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 262;
						((ExprOpContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==EQ || _la==NEQ) ) {
							((ExprOpContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 263;
						((ExprOpContext)_localctx).right = expr(11);
						}
						break;
					case 6:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 264;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 265;
						((ExprOpContext)_localctx).op = Match(AND);
						State = 266;
						((ExprOpContext)_localctx).right = expr(10);
						}
						break;
					case 7:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 267;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 268;
						((ExprOpContext)_localctx).op = Match(OR);
						State = 269;
						((ExprOpContext)_localctx).right = expr(9);
						}
						break;
					case 8:
						{
						_localctx = new MultiOpContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 270;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 271;
						Match(T__0);
						State = 272;
						expr(2);
						}
						break;
					}
					} 
				}
				State = 277;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class PairContext : ParserRuleContext {
		public ExprContext key;
		public ExprContext value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COL() { return GetToken(t2lParser.COL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public PairContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pair; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterPair(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitPair(this);
		}
	}

	[RuleVersion(0)]
	public PairContext pair() {
		PairContext _localctx = new PairContext(Context, State);
		EnterRule(_localctx, 44, RULE_pair);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 278;
			_localctx.key = expr(0);
			State = 279;
			Match(COL);
			State = 280;
			_localctx.value = expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
	 
		public AtomContext() { }
		public virtual void CopyFrom(AtomContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class IDAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		public IDAtomContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterIDAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitIDAtom(this);
		}
	}
	public partial class StringAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(t2lParser.STRING, 0); }
		public StringAtomContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterStringAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitStringAtom(this);
		}
	}
	public partial class ParenAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		public ParenAtomContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterParenAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitParenAtom(this);
		}
	}
	public partial class IntAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(t2lParser.INT, 0); }
		public IntAtomContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterIntAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitIntAtom(this);
		}
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 46, RULE_atom);
		try {
			State = 289;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPAR:
				_localctx = new ParenAtomContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 282;
				Match(OPAR);
				State = 283;
				expr(0);
				State = 284;
				Match(CPAR);
				}
				break;
			case INT:
				_localctx = new IntAtomContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 286;
				Match(INT);
				}
				break;
			case ID:
				_localctx = new IDAtomContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 287;
				Match(ID);
				}
				break;
			case STRING:
				_localctx = new StringAtomContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 288;
				Match(STRING);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 21: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 16);
		case 1: return Precpred(Context, 13);
		case 2: return Precpred(Context, 12);
		case 3: return Precpred(Context, 11);
		case 4: return Precpred(Context, 10);
		case 5: return Precpred(Context, 9);
		case 6: return Precpred(Context, 8);
		case 7: return Precpred(Context, 1);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,43,292,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,1,0,1,0,1,1,5,1,52,8,1,10,1,12,1,55,9,1,1,2,1,2,1,
		2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,68,8,2,1,3,1,3,1,3,3,3,73,8,3,1,
		4,1,4,1,4,1,4,1,4,1,4,1,5,3,5,82,8,5,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,
		6,1,7,1,7,1,7,1,7,1,7,5,7,98,8,7,10,7,12,7,101,9,7,1,7,1,7,3,7,105,8,7,
		1,7,1,7,5,7,109,8,7,10,7,12,7,112,9,7,1,7,1,7,1,8,1,8,1,8,5,8,119,8,8,
		10,8,12,8,122,9,8,1,8,3,8,125,8,8,1,9,1,9,5,9,129,8,9,10,9,12,9,132,9,
		9,1,9,3,9,135,8,9,1,10,1,10,1,10,1,10,1,10,1,10,1,10,3,10,144,8,10,1,11,
		1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,12,1,12,1,12,1,12,1,13,1,13,1,13,
		1,13,1,14,1,14,1,14,5,14,165,8,14,10,14,12,14,168,9,14,1,14,3,14,171,8,
		14,1,15,1,15,1,15,1,15,1,16,1,16,1,16,1,17,1,17,1,17,1,18,1,18,1,18,1,
		18,1,18,3,18,188,8,18,1,19,1,19,1,19,1,19,1,20,1,20,1,20,1,20,1,20,1,20,
		1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,5,21,210,8,21,10,21,
		12,21,213,9,21,1,21,3,21,216,8,21,1,21,1,21,1,21,1,21,1,21,5,21,223,8,
		21,10,21,12,21,226,9,21,1,21,3,21,229,8,21,1,21,1,21,1,21,1,21,1,21,1,
		21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,3,21,248,8,21,
		1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,
		1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,5,21,274,8,21,10,21,
		12,21,277,9,21,1,22,1,22,1,22,1,22,1,23,1,23,1,23,1,23,1,23,1,23,1,23,
		3,23,290,8,23,1,23,0,1,42,24,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,
		32,34,36,38,40,42,44,46,0,4,1,0,12,14,1,0,10,11,1,0,6,9,1,0,4,5,314,0,
		48,1,0,0,0,2,53,1,0,0,0,4,67,1,0,0,0,6,72,1,0,0,0,8,74,1,0,0,0,10,81,1,
		0,0,0,12,88,1,0,0,0,14,92,1,0,0,0,16,124,1,0,0,0,18,134,1,0,0,0,20,143,
		1,0,0,0,22,145,1,0,0,0,24,153,1,0,0,0,26,157,1,0,0,0,28,161,1,0,0,0,30,
		172,1,0,0,0,32,176,1,0,0,0,34,179,1,0,0,0,36,187,1,0,0,0,38,189,1,0,0,
		0,40,193,1,0,0,0,42,247,1,0,0,0,44,278,1,0,0,0,46,289,1,0,0,0,48,49,3,
		2,1,0,49,1,1,0,0,0,50,52,3,4,2,0,51,50,1,0,0,0,52,55,1,0,0,0,53,51,1,0,
		0,0,53,54,1,0,0,0,54,3,1,0,0,0,55,53,1,0,0,0,56,68,3,20,10,0,57,68,3,28,
		14,0,58,68,3,38,19,0,59,68,3,8,4,0,60,68,3,10,5,0,61,68,3,14,7,0,62,68,
		3,12,6,0,63,68,3,22,11,0,64,68,3,40,20,0,65,68,3,24,12,0,66,68,3,26,13,
		0,67,56,1,0,0,0,67,57,1,0,0,0,67,58,1,0,0,0,67,59,1,0,0,0,67,60,1,0,0,
		0,67,61,1,0,0,0,67,62,1,0,0,0,67,63,1,0,0,0,67,64,1,0,0,0,67,65,1,0,0,
		0,67,66,1,0,0,0,68,5,1,0,0,0,69,73,3,20,10,0,70,73,3,14,7,0,71,73,3,10,
		5,0,72,69,1,0,0,0,72,70,1,0,0,0,72,71,1,0,0,0,73,7,1,0,0,0,74,75,5,38,
		0,0,75,76,5,21,0,0,76,77,3,16,8,0,77,78,5,22,0,0,78,79,5,17,0,0,79,9,1,
		0,0,0,80,82,5,40,0,0,81,80,1,0,0,0,81,82,1,0,0,0,82,83,1,0,0,0,83,84,5,
		32,0,0,84,85,5,38,0,0,85,86,3,18,9,0,86,87,3,36,18,0,87,11,1,0,0,0,88,
		89,5,33,0,0,89,90,3,42,21,0,90,91,5,17,0,0,91,13,1,0,0,0,92,93,5,34,0,
		0,93,104,5,38,0,0,94,99,5,21,0,0,95,96,5,38,0,0,96,98,5,20,0,0,97,95,1,
		0,0,0,98,101,1,0,0,0,99,97,1,0,0,0,99,100,1,0,0,0,100,102,1,0,0,0,101,
		99,1,0,0,0,102,103,5,38,0,0,103,105,5,22,0,0,104,94,1,0,0,0,104,105,1,
		0,0,0,105,106,1,0,0,0,106,110,5,23,0,0,107,109,3,6,3,0,108,107,1,0,0,0,
		109,112,1,0,0,0,110,108,1,0,0,0,110,111,1,0,0,0,111,113,1,0,0,0,112,110,
		1,0,0,0,113,114,5,24,0,0,114,15,1,0,0,0,115,116,3,42,21,0,116,117,5,20,
		0,0,117,119,1,0,0,0,118,115,1,0,0,0,119,122,1,0,0,0,120,118,1,0,0,0,120,
		121,1,0,0,0,121,123,1,0,0,0,122,120,1,0,0,0,123,125,3,42,21,0,124,120,
		1,0,0,0,124,125,1,0,0,0,125,17,1,0,0,0,126,127,5,41,0,0,127,129,5,20,0,
		0,128,126,1,0,0,0,129,132,1,0,0,0,130,128,1,0,0,0,130,131,1,0,0,0,131,
		133,1,0,0,0,132,130,1,0,0,0,133,135,5,41,0,0,134,130,1,0,0,0,134,135,1,
		0,0,0,135,19,1,0,0,0,136,137,5,38,0,0,137,138,5,19,0,0,138,139,3,42,21,
		0,139,140,5,17,0,0,140,144,1,0,0,0,141,142,5,38,0,0,142,144,5,17,0,0,143,
		136,1,0,0,0,143,141,1,0,0,0,144,21,1,0,0,0,145,146,5,38,0,0,146,147,5,
		25,0,0,147,148,3,42,21,0,148,149,5,26,0,0,149,150,5,19,0,0,150,151,3,42,
		21,0,151,152,5,17,0,0,152,23,1,0,0,0,153,154,5,36,0,0,154,155,5,38,0,0,
		155,156,5,17,0,0,156,25,1,0,0,0,157,158,5,37,0,0,158,159,5,38,0,0,159,
		160,5,17,0,0,160,27,1,0,0,0,161,162,5,27,0,0,162,166,3,34,17,0,163,165,
		3,30,15,0,164,163,1,0,0,0,165,168,1,0,0,0,166,164,1,0,0,0,166,167,1,0,
		0,0,167,170,1,0,0,0,168,166,1,0,0,0,169,171,3,32,16,0,170,169,1,0,0,0,
		170,171,1,0,0,0,171,29,1,0,0,0,172,173,5,28,0,0,173,174,5,27,0,0,174,175,
		3,34,17,0,175,31,1,0,0,0,176,177,5,28,0,0,177,178,3,36,18,0,178,33,1,0,
		0,0,179,180,3,42,21,0,180,181,3,36,18,0,181,35,1,0,0,0,182,183,5,23,0,
		0,183,184,3,2,1,0,184,185,5,24,0,0,185,188,1,0,0,0,186,188,3,4,2,0,187,
		182,1,0,0,0,187,186,1,0,0,0,188,37,1,0,0,0,189,190,5,29,0,0,190,191,3,
		42,21,0,191,192,3,36,18,0,192,39,1,0,0,0,193,194,5,30,0,0,194,195,5,38,
		0,0,195,196,5,31,0,0,196,197,3,42,21,0,197,198,3,36,18,0,198,41,1,0,0,
		0,199,200,6,21,-1,0,200,201,5,11,0,0,201,248,3,42,21,15,202,203,5,16,0,
		0,203,248,3,42,21,14,204,248,3,46,23,0,205,215,5,25,0,0,206,207,3,42,21,
		0,207,208,5,20,0,0,208,210,1,0,0,0,209,206,1,0,0,0,210,213,1,0,0,0,211,
		209,1,0,0,0,211,212,1,0,0,0,212,214,1,0,0,0,213,211,1,0,0,0,214,216,3,
		42,21,0,215,211,1,0,0,0,215,216,1,0,0,0,216,217,1,0,0,0,217,248,5,26,0,
		0,218,228,5,23,0,0,219,220,3,44,22,0,220,221,5,20,0,0,221,223,1,0,0,0,
		222,219,1,0,0,0,223,226,1,0,0,0,224,222,1,0,0,0,224,225,1,0,0,0,225,227,
		1,0,0,0,226,224,1,0,0,0,227,229,3,44,22,0,228,224,1,0,0,0,228,229,1,0,
		0,0,229,230,1,0,0,0,230,248,5,24,0,0,231,232,5,38,0,0,232,233,5,25,0,0,
		233,234,3,42,21,0,234,235,5,26,0,0,235,248,1,0,0,0,236,237,5,38,0,0,237,
		238,5,21,0,0,238,239,3,16,8,0,239,240,5,22,0,0,240,248,1,0,0,0,241,242,
		5,35,0,0,242,243,5,38,0,0,243,244,5,21,0,0,244,245,3,16,8,0,245,246,5,
		22,0,0,246,248,1,0,0,0,247,199,1,0,0,0,247,202,1,0,0,0,247,204,1,0,0,0,
		247,205,1,0,0,0,247,218,1,0,0,0,247,231,1,0,0,0,247,236,1,0,0,0,247,241,
		1,0,0,0,248,275,1,0,0,0,249,250,10,16,0,0,250,251,5,15,0,0,251,274,3,42,
		21,16,252,253,10,13,0,0,253,254,7,0,0,0,254,274,3,42,21,14,255,256,10,
		12,0,0,256,257,7,1,0,0,257,274,3,42,21,13,258,259,10,11,0,0,259,260,7,
		2,0,0,260,274,3,42,21,12,261,262,10,10,0,0,262,263,7,3,0,0,263,274,3,42,
		21,11,264,265,10,9,0,0,265,266,5,3,0,0,266,274,3,42,21,10,267,268,10,8,
		0,0,268,269,5,2,0,0,269,274,3,42,21,9,270,271,10,1,0,0,271,272,5,1,0,0,
		272,274,3,42,21,2,273,249,1,0,0,0,273,252,1,0,0,0,273,255,1,0,0,0,273,
		258,1,0,0,0,273,261,1,0,0,0,273,264,1,0,0,0,273,267,1,0,0,0,273,270,1,
		0,0,0,274,277,1,0,0,0,275,273,1,0,0,0,275,276,1,0,0,0,276,43,1,0,0,0,277,
		275,1,0,0,0,278,279,3,42,21,0,279,280,5,18,0,0,280,281,3,42,21,0,281,45,
		1,0,0,0,282,283,5,21,0,0,283,284,3,42,21,0,284,285,5,22,0,0,285,290,1,
		0,0,0,286,290,5,39,0,0,287,290,5,38,0,0,288,290,5,41,0,0,289,282,1,0,0,
		0,289,286,1,0,0,0,289,287,1,0,0,0,289,288,1,0,0,0,290,47,1,0,0,0,23,53,
		67,72,81,99,104,110,120,124,130,134,143,166,170,187,211,215,224,228,247,
		273,275,289
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace T2L.Antlr
