# This is a basic workflow to help you get started with Actions

name: Issue Sorter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  issues:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.label.name == 'enhancement'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Move issues to project
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          repo-token: ${{ secrets.PROJECT_TOKEN }}
          project: Planned features
          column: To do
