//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../t2l.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace T2Lc.Antlr {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public partial class t2lParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, OR=2, AND=3, EQ=4, NEQ=5, GT=6, LT=7, GTEQ=8, LTEQ=9, PLUS=10, 
		MINUS=11, MULT=12, DIV=13, MOD=14, POW=15, NOT=16, SCOL=17, COL=18, ASSIGN=19, 
		COMMA=20, OPAR=21, CPAR=22, OBRACE=23, CBRACE=24, OSQUARE=25, CSQUARE=26, 
		IF=27, ELSE=28, WHILE=29, FOR=30, IN=31, FUNC=32, T2L_RETURN=33, CLASS=34, 
		NEW=35, IMPORT=36, JIMPORT=37, ID=38, INT=39, DOC=40, STRING=41, COMMENT=42, 
		SPACE=43;
	public const int
		RULE_start = 0, RULE_block = 1, RULE_stat = 2, RULE_class_stat_block = 3, 
		RULE_call_stat = 4, RULE_func_stat = 5, RULE_t2l_return = 6, RULE_class_stat = 7, 
		RULE_params = 8, RULE_def_params = 9, RULE_var = 10, RULE_index = 11, 
		RULE_import_stat = 12, RULE_if_stat = 13, RULE_elseIfStat = 14, RULE_elseStat = 15, 
		RULE_cond = 16, RULE_stat_block = 17, RULE_while_stat = 18, RULE_for_loop_stat = 19, 
		RULE_expr = 20, RULE_pair = 21, RULE_atom = 22;
	public static readonly string[] ruleNames = {
		"start", "block", "stat", "class_stat_block", "call_stat", "func_stat", 
		"t2l_return", "class_stat", "params", "def_params", "var", "index", "import_stat", 
		"if_stat", "elseIfStat", "elseStat", "cond", "stat_block", "while_stat", 
		"for_loop_stat", "expr", "pair", "atom"
	};

	private static readonly string[] _LiteralNames = {
		null, "'.'", "'||'", "'&&'", "'=='", "'!='", "'>'", "'<'", "'>='", "'<='", 
		"'+'", "'-'", "'*'", "'/'", "'%'", "'^'", "'!'", "';'", "':'", "'='", 
		"','", "'('", "')'", "'{'", "'}'", "'['", "']'", "'if'", "'else'", "'while'", 
		"'for'", "'in'", "'func'", "'return'", "'class'", "'new'", "'import'", 
		"'jimport'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "OR", "AND", "EQ", "NEQ", "GT", "LT", "GTEQ", "LTEQ", "PLUS", 
		"MINUS", "MULT", "DIV", "MOD", "POW", "NOT", "SCOL", "COL", "ASSIGN", 
		"COMMA", "OPAR", "CPAR", "OBRACE", "CBRACE", "OSQUARE", "CSQUARE", "IF", 
		"ELSE", "WHILE", "FOR", "IN", "FUNC", "T2L_RETURN", "CLASS", "NEW", "IMPORT", 
		"JIMPORT", "ID", "INT", "DOC", "STRING", "COMMENT", "SPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "t2l.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static t2lParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public t2lParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public t2lParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StartContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public StartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_start; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterStart(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitStart(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStart(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StartContext start() {
		StartContext _localctx = new StartContext(Context, State);
		EnterRule(_localctx, 0, RULE_start);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 46;
			block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatContext[] stat() {
			return GetRuleContexts<StatContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatContext stat(int i) {
			return GetRuleContext<StatContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF) | (1L << WHILE) | (1L << FOR) | (1L << FUNC) | (1L << T2L_RETURN) | (1L << CLASS) | (1L << IMPORT) | (1L << ID) | (1L << DOC))) != 0)) {
				{
				{
				State = 48;
				stat();
				}
				}
				State = 53;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VarContext var() {
			return GetRuleContext<VarContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public If_statContext if_stat() {
			return GetRuleContext<If_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public While_statContext while_stat() {
			return GetRuleContext<While_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Call_statContext call_stat() {
			return GetRuleContext<Call_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_statContext func_stat() {
			return GetRuleContext<Func_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_statContext class_stat() {
			return GetRuleContext<Class_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public T2l_returnContext t2l_return() {
			return GetRuleContext<T2l_returnContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IndexContext index() {
			return GetRuleContext<IndexContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public For_loop_statContext for_loop_stat() {
			return GetRuleContext<For_loop_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Import_statContext import_stat() {
			return GetRuleContext<Import_statContext>(0);
		}
		public StatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterStat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitStat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatContext stat() {
		StatContext _localctx = new StatContext(Context, State);
		EnterRule(_localctx, 4, RULE_stat);
		try {
			State = 64;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 54;
				var();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 55;
				if_stat();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 56;
				while_stat();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 57;
				call_stat();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 58;
				func_stat();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 59;
				class_stat();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 60;
				t2l_return();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 61;
				index();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 62;
				for_loop_stat();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 63;
				import_stat();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Class_stat_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VarContext var() {
			return GetRuleContext<VarContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_statContext class_stat() {
			return GetRuleContext<Class_statContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_statContext func_stat() {
			return GetRuleContext<Func_statContext>(0);
		}
		public Class_stat_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_class_stat_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterClass_stat_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitClass_stat_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClass_stat_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Class_stat_blockContext class_stat_block() {
		Class_stat_blockContext _localctx = new Class_stat_blockContext(Context, State);
		EnterRule(_localctx, 6, RULE_class_stat_block);
		try {
			State = 69;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 66;
				var();
				}
				break;
			case CLASS:
				EnterOuterAlt(_localctx, 2);
				{
				State = 67;
				class_stat();
				}
				break;
			case FUNC:
			case DOC:
				EnterOuterAlt(_localctx, 3);
				{
				State = 68;
				func_stat();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Call_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParamsContext @params() {
			return GetRuleContext<ParamsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public Call_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterCall_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitCall_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCall_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Call_statContext call_stat() {
		Call_statContext _localctx = new Call_statContext(Context, State);
		EnterRule(_localctx, 8, RULE_call_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71;
			Match(ID);
			State = 72;
			Match(OPAR);
			State = 73;
			@params();
			State = 74;
			Match(CPAR);
			State = 75;
			Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FUNC() { return GetToken(t2lParser.FUNC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Def_paramsContext def_params() {
			return GetRuleContext<Def_paramsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOC() { return GetToken(t2lParser.DOC, 0); }
		public Func_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterFunc_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitFunc_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_statContext func_stat() {
		Func_statContext _localctx = new Func_statContext(Context, State);
		EnterRule(_localctx, 10, RULE_func_stat);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DOC) {
				{
				State = 77;
				Match(DOC);
				}
			}

			State = 80;
			Match(FUNC);
			State = 81;
			Match(ID);
			State = 82;
			Match(OPAR);
			State = 83;
			def_params();
			State = 84;
			Match(CPAR);
			State = 85;
			stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class T2l_returnContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T2L_RETURN() { return GetToken(t2lParser.T2L_RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public T2l_returnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_t2l_return; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterT2l_return(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitT2l_return(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitT2l_return(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public T2l_returnContext t2l_return() {
		T2l_returnContext _localctx = new T2l_returnContext(Context, State);
		EnterRule(_localctx, 12, RULE_t2l_return);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			Match(T2L_RETURN);
			State = 88;
			expr(0);
			State = 89;
			Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Class_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(t2lParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(t2lParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(t2lParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBRACE() { return GetToken(t2lParser.OBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CBRACE() { return GetToken(t2lParser.CBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Class_stat_blockContext[] class_stat_block() {
			return GetRuleContexts<Class_stat_blockContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Class_stat_blockContext class_stat_block(int i) {
			return GetRuleContext<Class_stat_blockContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(t2lParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(t2lParser.COMMA, i);
		}
		public Class_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_class_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterClass_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitClass_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClass_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Class_statContext class_stat() {
		Class_statContext _localctx = new Class_statContext(Context, State);
		EnterRule(_localctx, 14, RULE_class_stat);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 91;
			Match(CLASS);
			State = 92;
			Match(ID);
			State = 103;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==OPAR) {
				{
				State = 93;
				Match(OPAR);
				State = 98;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 94;
						Match(ID);
						State = 95;
						Match(COMMA);
						}
						} 
					}
					State = 100;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				}
				State = 101;
				Match(ID);
				State = 102;
				Match(CPAR);
				}
			}

			State = 105;
			Match(OBRACE);
			State = 109;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << FUNC) | (1L << CLASS) | (1L << ID) | (1L << DOC))) != 0)) {
				{
				{
				State = 106;
				class_stat_block();
				}
				}
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 112;
			Match(CBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParamsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(t2lParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(t2lParser.COMMA, i);
		}
		public ParamsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_params; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterParams(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitParams(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParams(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParamsContext @params() {
		ParamsContext _localctx = new ParamsContext(Context, State);
		EnterRule(_localctx, 16, RULE_params);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 123;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MINUS) | (1L << NOT) | (1L << OPAR) | (1L << OBRACE) | (1L << OSQUARE) | (1L << NEW) | (1L << ID) | (1L << INT) | (1L << STRING))) != 0)) {
				{
				State = 119;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 114;
						expr(0);
						State = 115;
						Match(COMMA);
						}
						} 
					}
					State = 121;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
				}
				State = 122;
				expr(0);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Def_paramsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(t2lParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(t2lParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(t2lParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(t2lParser.COMMA, i);
		}
		public Def_paramsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_def_params; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterDef_params(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitDef_params(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDef_params(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Def_paramsContext def_params() {
		Def_paramsContext _localctx = new Def_paramsContext(Context, State);
		EnterRule(_localctx, 18, RULE_def_params);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 129;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 125;
						Match(ID);
						State = 126;
						Match(COMMA);
						}
						} 
					}
					State = 131;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
				}
				State = 132;
				Match(ID);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(t2lParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public VarContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterVar(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitVar(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VarContext var() {
		VarContext _localctx = new VarContext(Context, State);
		EnterRule(_localctx, 20, RULE_var);
		try {
			State = 142;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 135;
				Match(ID);
				State = 136;
				Match(ASSIGN);
				State = 137;
				expr(0);
				State = 138;
				Match(SCOL);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 140;
				Match(ID);
				State = 141;
				Match(SCOL);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IndexContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OSQUARE() { return GetToken(t2lParser.OSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CSQUARE() { return GetToken(t2lParser.CSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(t2lParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public IndexContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_index; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterIndex(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitIndex(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIndex(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IndexContext index() {
		IndexContext _localctx = new IndexContext(Context, State);
		EnterRule(_localctx, 22, RULE_index);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 144;
			Match(ID);
			State = 145;
			Match(OSQUARE);
			State = 146;
			expr(0);
			State = 147;
			Match(CSQUARE);
			State = 148;
			Match(ASSIGN);
			State = 149;
			expr(0);
			State = 150;
			Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Import_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IMPORT() { return GetToken(t2lParser.IMPORT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SCOL() { return GetToken(t2lParser.SCOL, 0); }
		public Import_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_import_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterImport_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitImport_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImport_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Import_statContext import_stat() {
		Import_statContext _localctx = new Import_statContext(Context, State);
		EnterRule(_localctx, 24, RULE_import_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152;
			Match(IMPORT);
			State = 153;
			Match(ID);
			State = 154;
			Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class If_statContext : ParserRuleContext {
		public ElseIfStatContext ElseIf;
		public ElseStatContext Else;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(t2lParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CondContext cond() {
			return GetRuleContext<CondContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElseIfStatContext[] elseIfStat() {
			return GetRuleContexts<ElseIfStatContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElseIfStatContext elseIfStat(int i) {
			return GetRuleContext<ElseIfStatContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElseStatContext elseStat() {
			return GetRuleContext<ElseStatContext>(0);
		}
		public If_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterIf_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitIf_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public If_statContext if_stat() {
		If_statContext _localctx = new If_statContext(Context, State);
		EnterRule(_localctx, 26, RULE_if_stat);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 156;
			Match(IF);
			State = 157;
			cond();
			State = 161;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 158;
					_localctx.ElseIf = elseIfStat();
					}
					} 
				}
				State = 163;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			}
			State = 165;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 164;
				_localctx.Else = elseStat();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElseIfStatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(t2lParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(t2lParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CondContext cond() {
			return GetRuleContext<CondContext>(0);
		}
		public ElseIfStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elseIfStat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterElseIfStat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitElseIfStat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElseIfStat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElseIfStatContext elseIfStat() {
		ElseIfStatContext _localctx = new ElseIfStatContext(Context, State);
		EnterRule(_localctx, 28, RULE_elseIfStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167;
			Match(ELSE);
			State = 168;
			Match(IF);
			State = 169;
			cond();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElseStatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(t2lParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public ElseStatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elseStat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterElseStat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitElseStat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElseStat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElseStatContext elseStat() {
		ElseStatContext _localctx = new ElseStatContext(Context, State);
		EnterRule(_localctx, 30, RULE_elseStat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171;
			Match(ELSE);
			State = 172;
			stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CondContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public CondContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cond; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterCond(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitCond(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCond(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CondContext cond() {
		CondContext _localctx = new CondContext(Context, State);
		EnterRule(_localctx, 32, RULE_cond);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 174;
			expr(0);
			State = 175;
			stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Stat_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBRACE() { return GetToken(t2lParser.OBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CBRACE() { return GetToken(t2lParser.CBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatContext stat() {
			return GetRuleContext<StatContext>(0);
		}
		public Stat_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stat_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterStat_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitStat_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStat_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Stat_blockContext stat_block() {
		Stat_blockContext _localctx = new Stat_blockContext(Context, State);
		EnterRule(_localctx, 34, RULE_stat_block);
		try {
			State = 182;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OBRACE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 177;
				Match(OBRACE);
				State = 178;
				block();
				State = 179;
				Match(CBRACE);
				}
				break;
			case IF:
			case WHILE:
			case FOR:
			case FUNC:
			case T2L_RETURN:
			case CLASS:
			case IMPORT:
			case ID:
			case DOC:
				EnterOuterAlt(_localctx, 2);
				{
				State = 181;
				stat();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class While_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(t2lParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public While_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterWhile_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitWhile_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public While_statContext while_stat() {
		While_statContext _localctx = new While_statContext(Context, State);
		EnterRule(_localctx, 36, RULE_while_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			Match(WHILE);
			State = 185;
			expr(0);
			State = 186;
			stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_loop_statContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR() { return GetToken(t2lParser.FOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IN() { return GetToken(t2lParser.IN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public For_loop_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_loop_stat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterFor_loop_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitFor_loop_stat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor_loop_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public For_loop_statContext for_loop_stat() {
		For_loop_statContext _localctx = new For_loop_statContext(Context, State);
		EnterRule(_localctx, 38, RULE_for_loop_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			Match(FOR);
			State = 189;
			Match(ID);
			State = 190;
			Match(IN);
			State = 191;
			expr(0);
			State = 192;
			stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DictionaryOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBRACE() { return GetToken(t2lParser.OBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CBRACE() { return GetToken(t2lParser.CBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(t2lParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(t2lParser.COMMA, i);
		}
		public DictionaryOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterDictionaryOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitDictionaryOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDictionaryOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ClassOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW() { return GetToken(t2lParser.NEW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParamsContext @params() {
			return GetRuleContext<ParamsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		public ClassOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterClassOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitClassOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ListOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OSQUARE() { return GetToken(t2lParser.OSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CSQUARE() { return GetToken(t2lParser.CSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(t2lParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(t2lParser.COMMA, i);
		}
		public ListOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterListOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitListOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitListOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParamsContext @params() {
			return GetRuleContext<ParamsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		public FuncOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterFuncOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitFuncOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AtomOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public AtomOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterAtomOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitAtomOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAtomOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MultiOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public MultiOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterMultiOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitMultiOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExprOpContext : ExprContext {
		public ExprContext left;
		public IToken op;
		public ExprContext right;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode POW() { return GetToken(t2lParser.POW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT() { return GetToken(t2lParser.MULT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(t2lParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD() { return GetToken(t2lParser.MOD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(t2lParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(t2lParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LTEQ() { return GetToken(t2lParser.LTEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GTEQ() { return GetToken(t2lParser.GTEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(t2lParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(t2lParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(t2lParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEQ() { return GetToken(t2lParser.NEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(t2lParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(t2lParser.OR, 0); }
		public ExprOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitExprOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SingleOpContext : ExprContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(t2lParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(t2lParser.NOT, 0); }
		public SingleOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterSingleOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitSingleOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSingleOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IndexOpContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OSQUARE() { return GetToken(t2lParser.OSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CSQUARE() { return GetToken(t2lParser.CSQUARE, 0); }
		public IndexOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterIndexOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitIndexOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIndexOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 40;
		EnterRecursionRule(_localctx, 40, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 242;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				{
				_localctx = new SingleOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 195;
				((SingleOpContext)_localctx).op = Match(MINUS);
				State = 196;
				expr(15);
				}
				break;
			case 2:
				{
				_localctx = new SingleOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 197;
				((SingleOpContext)_localctx).op = Match(NOT);
				State = 198;
				expr(14);
				}
				break;
			case 3:
				{
				_localctx = new AtomOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 199;
				atom();
				}
				break;
			case 4:
				{
				_localctx = new ListOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 200;
				Match(OSQUARE);
				State = 210;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MINUS) | (1L << NOT) | (1L << OPAR) | (1L << OBRACE) | (1L << OSQUARE) | (1L << NEW) | (1L << ID) | (1L << INT) | (1L << STRING))) != 0)) {
					{
					State = 206;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
					while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
						if ( _alt==1 ) {
							{
							{
							State = 201;
							expr(0);
							State = 202;
							Match(COMMA);
							}
							} 
						}
						State = 208;
						ErrorHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
					}
					State = 209;
					expr(0);
					}
				}

				State = 212;
				Match(CSQUARE);
				}
				break;
			case 5:
				{
				_localctx = new DictionaryOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 213;
				Match(OBRACE);
				State = 223;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MINUS) | (1L << NOT) | (1L << OPAR) | (1L << OBRACE) | (1L << OSQUARE) | (1L << NEW) | (1L << ID) | (1L << INT) | (1L << STRING))) != 0)) {
					{
					State = 219;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
					while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
						if ( _alt==1 ) {
							{
							{
							State = 214;
							pair();
							State = 215;
							Match(COMMA);
							}
							} 
						}
						State = 221;
						ErrorHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
					}
					State = 222;
					pair();
					}
				}

				State = 225;
				Match(CBRACE);
				}
				break;
			case 6:
				{
				_localctx = new IndexOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 226;
				Match(ID);
				State = 227;
				Match(OSQUARE);
				State = 228;
				expr(0);
				State = 229;
				Match(CSQUARE);
				}
				break;
			case 7:
				{
				_localctx = new FuncOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 231;
				Match(ID);
				State = 232;
				Match(OPAR);
				State = 233;
				@params();
				State = 234;
				Match(CPAR);
				}
				break;
			case 8:
				{
				_localctx = new ClassOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 236;
				Match(NEW);
				State = 237;
				Match(ID);
				State = 238;
				Match(OPAR);
				State = 239;
				@params();
				State = 240;
				Match(CPAR);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 270;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 268;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
					case 1:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 244;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 245;
						((ExprOpContext)_localctx).op = Match(POW);
						State = 246;
						((ExprOpContext)_localctx).right = expr(16);
						}
						break;
					case 2:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 247;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 248;
						((ExprOpContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MULT) | (1L << DIV) | (1L << MOD))) != 0)) ) {
							((ExprOpContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 249;
						((ExprOpContext)_localctx).right = expr(14);
						}
						break;
					case 3:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 250;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 251;
						((ExprOpContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((ExprOpContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 252;
						((ExprOpContext)_localctx).right = expr(13);
						}
						break;
					case 4:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 253;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 254;
						((ExprOpContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << GT) | (1L << LT) | (1L << GTEQ) | (1L << LTEQ))) != 0)) ) {
							((ExprOpContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 255;
						((ExprOpContext)_localctx).right = expr(12);
						}
						break;
					case 5:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 256;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 257;
						((ExprOpContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==EQ || _la==NEQ) ) {
							((ExprOpContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 258;
						((ExprOpContext)_localctx).right = expr(11);
						}
						break;
					case 6:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 259;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 260;
						((ExprOpContext)_localctx).op = Match(AND);
						State = 261;
						((ExprOpContext)_localctx).right = expr(10);
						}
						break;
					case 7:
						{
						_localctx = new ExprOpContext(new ExprContext(_parentctx, _parentState));
						((ExprOpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 262;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 263;
						((ExprOpContext)_localctx).op = Match(OR);
						State = 264;
						((ExprOpContext)_localctx).right = expr(9);
						}
						break;
					case 8:
						{
						_localctx = new MultiOpContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 265;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 266;
						Match(T__0);
						State = 267;
						expr(2);
						}
						break;
					}
					} 
				}
				State = 272;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class PairContext : ParserRuleContext {
		public ExprContext key;
		public ExprContext value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COL() { return GetToken(t2lParser.COL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public PairContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pair; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterPair(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitPair(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPair(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PairContext pair() {
		PairContext _localctx = new PairContext(Context, State);
		EnterRule(_localctx, 42, RULE_pair);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 273;
			_localctx.key = expr(0);
			State = 274;
			Match(COL);
			State = 275;
			_localctx.value = expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
	 
		public AtomContext() { }
		public virtual void CopyFrom(AtomContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class IDAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(t2lParser.ID, 0); }
		public IDAtomContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterIDAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitIDAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIDAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(t2lParser.STRING, 0); }
		public StringAtomContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterStringAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitStringAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPAR() { return GetToken(t2lParser.OPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CPAR() { return GetToken(t2lParser.CPAR, 0); }
		public ParenAtomContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterParenAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitParenAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntAtomContext : AtomContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(t2lParser.INT, 0); }
		public IntAtomContext(AtomContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.EnterIntAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			It2lListener typedListener = listener as It2lListener;
			if (typedListener != null) typedListener.ExitIntAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			It2lVisitor<TResult> typedVisitor = visitor as It2lVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntAtom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 44, RULE_atom);
		try {
			State = 284;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPAR:
				_localctx = new ParenAtomContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 277;
				Match(OPAR);
				State = 278;
				expr(0);
				State = 279;
				Match(CPAR);
				}
				break;
			case INT:
				_localctx = new IntAtomContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 281;
				Match(INT);
				}
				break;
			case ID:
				_localctx = new IDAtomContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 282;
				Match(ID);
				}
				break;
			case STRING:
				_localctx = new StringAtomContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 283;
				Match(STRING);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 20: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 16);
		case 1: return Precpred(Context, 13);
		case 2: return Precpred(Context, 12);
		case 3: return Precpred(Context, 11);
		case 4: return Precpred(Context, 10);
		case 5: return Precpred(Context, 9);
		case 6: return Precpred(Context, 8);
		case 7: return Precpred(Context, 1);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,43,287,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,1,0,1,0,1,1,5,1,50,8,1,10,1,12,1,53,9,1,1,2,1,2,1,2,1,2,1,2,
		1,2,1,2,1,2,1,2,1,2,3,2,65,8,2,1,3,1,3,1,3,3,3,70,8,3,1,4,1,4,1,4,1,4,
		1,4,1,4,1,5,3,5,79,8,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,1,7,
		1,7,1,7,1,7,1,7,5,7,97,8,7,10,7,12,7,100,9,7,1,7,1,7,3,7,104,8,7,1,7,1,
		7,5,7,108,8,7,10,7,12,7,111,9,7,1,7,1,7,1,8,1,8,1,8,5,8,118,8,8,10,8,12,
		8,121,9,8,1,8,3,8,124,8,8,1,9,1,9,5,9,128,8,9,10,9,12,9,131,9,9,1,9,3,
		9,134,8,9,1,10,1,10,1,10,1,10,1,10,1,10,1,10,3,10,143,8,10,1,11,1,11,1,
		11,1,11,1,11,1,11,1,11,1,11,1,12,1,12,1,12,1,12,1,13,1,13,1,13,5,13,160,
		8,13,10,13,12,13,163,9,13,1,13,3,13,166,8,13,1,14,1,14,1,14,1,14,1,15,
		1,15,1,15,1,16,1,16,1,16,1,17,1,17,1,17,1,17,1,17,3,17,183,8,17,1,18,1,
		18,1,18,1,18,1,19,1,19,1,19,1,19,1,19,1,19,1,20,1,20,1,20,1,20,1,20,1,
		20,1,20,1,20,1,20,1,20,5,20,205,8,20,10,20,12,20,208,9,20,1,20,3,20,211,
		8,20,1,20,1,20,1,20,1,20,1,20,5,20,218,8,20,10,20,12,20,221,9,20,1,20,
		3,20,224,8,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,
		20,1,20,1,20,1,20,1,20,1,20,3,20,243,8,20,1,20,1,20,1,20,1,20,1,20,1,20,
		1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,
		1,20,1,20,1,20,1,20,5,20,269,8,20,10,20,12,20,272,9,20,1,21,1,21,1,21,
		1,21,1,22,1,22,1,22,1,22,1,22,1,22,1,22,3,22,285,8,22,1,22,0,1,40,23,0,
		2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,0,4,1,0,
		12,14,1,0,10,11,1,0,6,9,1,0,4,5,309,0,46,1,0,0,0,2,51,1,0,0,0,4,64,1,0,
		0,0,6,69,1,0,0,0,8,71,1,0,0,0,10,78,1,0,0,0,12,87,1,0,0,0,14,91,1,0,0,
		0,16,123,1,0,0,0,18,133,1,0,0,0,20,142,1,0,0,0,22,144,1,0,0,0,24,152,1,
		0,0,0,26,156,1,0,0,0,28,167,1,0,0,0,30,171,1,0,0,0,32,174,1,0,0,0,34,182,
		1,0,0,0,36,184,1,0,0,0,38,188,1,0,0,0,40,242,1,0,0,0,42,273,1,0,0,0,44,
		284,1,0,0,0,46,47,3,2,1,0,47,1,1,0,0,0,48,50,3,4,2,0,49,48,1,0,0,0,50,
		53,1,0,0,0,51,49,1,0,0,0,51,52,1,0,0,0,52,3,1,0,0,0,53,51,1,0,0,0,54,65,
		3,20,10,0,55,65,3,26,13,0,56,65,3,36,18,0,57,65,3,8,4,0,58,65,3,10,5,0,
		59,65,3,14,7,0,60,65,3,12,6,0,61,65,3,22,11,0,62,65,3,38,19,0,63,65,3,
		24,12,0,64,54,1,0,0,0,64,55,1,0,0,0,64,56,1,0,0,0,64,57,1,0,0,0,64,58,
		1,0,0,0,64,59,1,0,0,0,64,60,1,0,0,0,64,61,1,0,0,0,64,62,1,0,0,0,64,63,
		1,0,0,0,65,5,1,0,0,0,66,70,3,20,10,0,67,70,3,14,7,0,68,70,3,10,5,0,69,
		66,1,0,0,0,69,67,1,0,0,0,69,68,1,0,0,0,70,7,1,0,0,0,71,72,5,38,0,0,72,
		73,5,21,0,0,73,74,3,16,8,0,74,75,5,22,0,0,75,76,5,17,0,0,76,9,1,0,0,0,
		77,79,5,40,0,0,78,77,1,0,0,0,78,79,1,0,0,0,79,80,1,0,0,0,80,81,5,32,0,
		0,81,82,5,38,0,0,82,83,5,21,0,0,83,84,3,18,9,0,84,85,5,22,0,0,85,86,3,
		34,17,0,86,11,1,0,0,0,87,88,5,33,0,0,88,89,3,40,20,0,89,90,5,17,0,0,90,
		13,1,0,0,0,91,92,5,34,0,0,92,103,5,38,0,0,93,98,5,21,0,0,94,95,5,38,0,
		0,95,97,5,20,0,0,96,94,1,0,0,0,97,100,1,0,0,0,98,96,1,0,0,0,98,99,1,0,
		0,0,99,101,1,0,0,0,100,98,1,0,0,0,101,102,5,38,0,0,102,104,5,22,0,0,103,
		93,1,0,0,0,103,104,1,0,0,0,104,105,1,0,0,0,105,109,5,23,0,0,106,108,3,
		6,3,0,107,106,1,0,0,0,108,111,1,0,0,0,109,107,1,0,0,0,109,110,1,0,0,0,
		110,112,1,0,0,0,111,109,1,0,0,0,112,113,5,24,0,0,113,15,1,0,0,0,114,115,
		3,40,20,0,115,116,5,20,0,0,116,118,1,0,0,0,117,114,1,0,0,0,118,121,1,0,
		0,0,119,117,1,0,0,0,119,120,1,0,0,0,120,122,1,0,0,0,121,119,1,0,0,0,122,
		124,3,40,20,0,123,119,1,0,0,0,123,124,1,0,0,0,124,17,1,0,0,0,125,126,5,
		38,0,0,126,128,5,20,0,0,127,125,1,0,0,0,128,131,1,0,0,0,129,127,1,0,0,
		0,129,130,1,0,0,0,130,132,1,0,0,0,131,129,1,0,0,0,132,134,5,38,0,0,133,
		129,1,0,0,0,133,134,1,0,0,0,134,19,1,0,0,0,135,136,5,38,0,0,136,137,5,
		19,0,0,137,138,3,40,20,0,138,139,5,17,0,0,139,143,1,0,0,0,140,141,5,38,
		0,0,141,143,5,17,0,0,142,135,1,0,0,0,142,140,1,0,0,0,143,21,1,0,0,0,144,
		145,5,38,0,0,145,146,5,25,0,0,146,147,3,40,20,0,147,148,5,26,0,0,148,149,
		5,19,0,0,149,150,3,40,20,0,150,151,5,17,0,0,151,23,1,0,0,0,152,153,5,36,
		0,0,153,154,5,38,0,0,154,155,5,17,0,0,155,25,1,0,0,0,156,157,5,27,0,0,
		157,161,3,32,16,0,158,160,3,28,14,0,159,158,1,0,0,0,160,163,1,0,0,0,161,
		159,1,0,0,0,161,162,1,0,0,0,162,165,1,0,0,0,163,161,1,0,0,0,164,166,3,
		30,15,0,165,164,1,0,0,0,165,166,1,0,0,0,166,27,1,0,0,0,167,168,5,28,0,
		0,168,169,5,27,0,0,169,170,3,32,16,0,170,29,1,0,0,0,171,172,5,28,0,0,172,
		173,3,34,17,0,173,31,1,0,0,0,174,175,3,40,20,0,175,176,3,34,17,0,176,33,
		1,0,0,0,177,178,5,23,0,0,178,179,3,2,1,0,179,180,5,24,0,0,180,183,1,0,
		0,0,181,183,3,4,2,0,182,177,1,0,0,0,182,181,1,0,0,0,183,35,1,0,0,0,184,
		185,5,29,0,0,185,186,3,40,20,0,186,187,3,34,17,0,187,37,1,0,0,0,188,189,
		5,30,0,0,189,190,5,38,0,0,190,191,5,31,0,0,191,192,3,40,20,0,192,193,3,
		34,17,0,193,39,1,0,0,0,194,195,6,20,-1,0,195,196,5,11,0,0,196,243,3,40,
		20,15,197,198,5,16,0,0,198,243,3,40,20,14,199,243,3,44,22,0,200,210,5,
		25,0,0,201,202,3,40,20,0,202,203,5,20,0,0,203,205,1,0,0,0,204,201,1,0,
		0,0,205,208,1,0,0,0,206,204,1,0,0,0,206,207,1,0,0,0,207,209,1,0,0,0,208,
		206,1,0,0,0,209,211,3,40,20,0,210,206,1,0,0,0,210,211,1,0,0,0,211,212,
		1,0,0,0,212,243,5,26,0,0,213,223,5,23,0,0,214,215,3,42,21,0,215,216,5,
		20,0,0,216,218,1,0,0,0,217,214,1,0,0,0,218,221,1,0,0,0,219,217,1,0,0,0,
		219,220,1,0,0,0,220,222,1,0,0,0,221,219,1,0,0,0,222,224,3,42,21,0,223,
		219,1,0,0,0,223,224,1,0,0,0,224,225,1,0,0,0,225,243,5,24,0,0,226,227,5,
		38,0,0,227,228,5,25,0,0,228,229,3,40,20,0,229,230,5,26,0,0,230,243,1,0,
		0,0,231,232,5,38,0,0,232,233,5,21,0,0,233,234,3,16,8,0,234,235,5,22,0,
		0,235,243,1,0,0,0,236,237,5,35,0,0,237,238,5,38,0,0,238,239,5,21,0,0,239,
		240,3,16,8,0,240,241,5,22,0,0,241,243,1,0,0,0,242,194,1,0,0,0,242,197,
		1,0,0,0,242,199,1,0,0,0,242,200,1,0,0,0,242,213,1,0,0,0,242,226,1,0,0,
		0,242,231,1,0,0,0,242,236,1,0,0,0,243,270,1,0,0,0,244,245,10,16,0,0,245,
		246,5,15,0,0,246,269,3,40,20,16,247,248,10,13,0,0,248,249,7,0,0,0,249,
		269,3,40,20,14,250,251,10,12,0,0,251,252,7,1,0,0,252,269,3,40,20,13,253,
		254,10,11,0,0,254,255,7,2,0,0,255,269,3,40,20,12,256,257,10,10,0,0,257,
		258,7,3,0,0,258,269,3,40,20,11,259,260,10,9,0,0,260,261,5,3,0,0,261,269,
		3,40,20,10,262,263,10,8,0,0,263,264,5,2,0,0,264,269,3,40,20,9,265,266,
		10,1,0,0,266,267,5,1,0,0,267,269,3,40,20,2,268,244,1,0,0,0,268,247,1,0,
		0,0,268,250,1,0,0,0,268,253,1,0,0,0,268,256,1,0,0,0,268,259,1,0,0,0,268,
		262,1,0,0,0,268,265,1,0,0,0,269,272,1,0,0,0,270,268,1,0,0,0,270,271,1,
		0,0,0,271,41,1,0,0,0,272,270,1,0,0,0,273,274,3,40,20,0,274,275,5,18,0,
		0,275,276,3,40,20,0,276,43,1,0,0,0,277,278,5,21,0,0,278,279,3,40,20,0,
		279,280,5,22,0,0,280,285,1,0,0,0,281,285,5,39,0,0,282,285,5,38,0,0,283,
		285,5,41,0,0,284,277,1,0,0,0,284,281,1,0,0,0,284,282,1,0,0,0,284,283,1,
		0,0,0,285,45,1,0,0,0,23,51,64,69,78,98,103,109,119,123,129,133,142,161,
		165,182,206,210,219,223,242,268,270,284
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace T2Lc.Antlr
