//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../t2l.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace T2Lc.Antlr {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="t2lParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface It2lVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] t2lParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] t2lParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat([NotNull] t2lParser.StatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.class_stat_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_stat_block([NotNull] t2lParser.Class_stat_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.call_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_stat([NotNull] t2lParser.Call_statContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.func_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_stat([NotNull] t2lParser.Func_statContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.t2l_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitT2l_return([NotNull] t2lParser.T2l_returnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.class_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_stat([NotNull] t2lParser.Class_statContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParams([NotNull] t2lParser.ParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.def_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDef_params([NotNull] t2lParser.Def_paramsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] t2lParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex([NotNull] t2lParser.IndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.import_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_stat([NotNull] t2lParser.Import_statContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.if_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_stat([NotNull] t2lParser.If_statContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.elseIfStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfStat([NotNull] t2lParser.ElseIfStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.elseStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStat([NotNull] t2lParser.ElseStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCond([NotNull] t2lParser.CondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.stat_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat_block([NotNull] t2lParser.Stat_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.while_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_stat([NotNull] t2lParser.While_statContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.for_loop_stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_loop_stat([NotNull] t2lParser.For_loop_statContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DictionaryOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionaryOp([NotNull] t2lParser.DictionaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassOp([NotNull] t2lParser.ClassOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ListOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListOp([NotNull] t2lParser.ListOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncOp([NotNull] t2lParser.FuncOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AtomOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomOp([NotNull] t2lParser.AtomOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultiOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiOp([NotNull] t2lParser.MultiOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExprOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprOp([NotNull] t2lParser.ExprOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SingleOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleOp([NotNull] t2lParser.SingleOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IndexOp</c>
	/// labeled alternative in <see cref="t2lParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexOp([NotNull] t2lParser.IndexOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="t2lParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPair([NotNull] t2lParser.PairContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenAtom([NotNull] t2lParser.ParenAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntAtom([NotNull] t2lParser.IntAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IDAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIDAtom([NotNull] t2lParser.IDAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringAtom</c>
	/// labeled alternative in <see cref="t2lParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringAtom([NotNull] t2lParser.StringAtomContext context);
}
} // namespace T2Lc.Antlr
